/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Course = IDL.Record({
  'title' : IDL.Text,
  'subjectTags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const LiveClass = IDL.Record({
  'title' : IDL.Text,
  'scheduledTime' : Time,
  'teacher' : IDL.Text,
  'isLive' : IDL.Bool,
});
export const StudyMaterial = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'chapter' : IDL.Text,
});
export const TestSeries = IDL.Record({
  'totalMarks' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StudentProgress = IDL.Record({
  'completionPercentage' : IDL.Nat,
  'enrolledCourses' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCourse' : IDL.Func([Course], [IDL.Nat], []),
  'addLiveClass' : IDL.Func([LiveClass], [IDL.Nat], []),
  'addStudyMaterial' : IDL.Func([StudyMaterial], [IDL.Nat], []),
  'addTestSeries' : IDL.Func([TestSeries], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCourse' : IDL.Func([IDL.Nat], [], []),
  'deleteLiveClass' : IDL.Func([IDL.Nat], [], []),
  'deleteStudyMaterial' : IDL.Func([IDL.Nat], [], []),
  'deleteTestSeries' : IDL.Func([IDL.Nat], [], []),
  'enrollInCourse' : IDL.Func([IDL.Nat], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllCoursesSortedByTitle' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Course))],
      ['query'],
    ),
  'getAllLiveClasses' : IDL.Func([], [IDL.Vec(LiveClass)], ['query']),
  'getAllLiveClassesSortedByTime' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, LiveClass))],
      ['query'],
    ),
  'getAllStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
  'getAllStudyMaterialsSortedByTitle' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, StudyMaterial))],
      ['query'],
    ),
  'getAllTestSeries' : IDL.Func([], [IDL.Vec(TestSeries)], ['query']),
  'getAllTestSeriesSortedByTitle' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, TestSeries))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourseById' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getLiveClassById' : IDL.Func([IDL.Nat], [IDL.Opt(LiveClass)], ['query']),
  'getMyProgress' : IDL.Func([], [IDL.Opt(StudentProgress)], ['query']),
  'getStudyMaterialById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(StudyMaterial)],
      ['query'],
    ),
  'getTestSeriesById' : IDL.Func([IDL.Nat], [IDL.Opt(TestSeries)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSampleData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCompletionPercentage' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateCourse' : IDL.Func([IDL.Nat, Course], [], []),
  'updateLiveClass' : IDL.Func([IDL.Nat, LiveClass], [], []),
  'updateStudyMaterial' : IDL.Func([IDL.Nat, StudyMaterial], [], []),
  'updateTestSeries' : IDL.Func([IDL.Nat, TestSeries], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Course = IDL.Record({
    'title' : IDL.Text,
    'subjectTags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const LiveClass = IDL.Record({
    'title' : IDL.Text,
    'scheduledTime' : Time,
    'teacher' : IDL.Text,
    'isLive' : IDL.Bool,
  });
  const StudyMaterial = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'chapter' : IDL.Text,
  });
  const TestSeries = IDL.Record({
    'totalMarks' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StudentProgress = IDL.Record({
    'completionPercentage' : IDL.Nat,
    'enrolledCourses' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCourse' : IDL.Func([Course], [IDL.Nat], []),
    'addLiveClass' : IDL.Func([LiveClass], [IDL.Nat], []),
    'addStudyMaterial' : IDL.Func([StudyMaterial], [IDL.Nat], []),
    'addTestSeries' : IDL.Func([TestSeries], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCourse' : IDL.Func([IDL.Nat], [], []),
    'deleteLiveClass' : IDL.Func([IDL.Nat], [], []),
    'deleteStudyMaterial' : IDL.Func([IDL.Nat], [], []),
    'deleteTestSeries' : IDL.Func([IDL.Nat], [], []),
    'enrollInCourse' : IDL.Func([IDL.Nat], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllCoursesSortedByTitle' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Course))],
        ['query'],
      ),
    'getAllLiveClasses' : IDL.Func([], [IDL.Vec(LiveClass)], ['query']),
    'getAllLiveClassesSortedByTime' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, LiveClass))],
        ['query'],
      ),
    'getAllStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
    'getAllStudyMaterialsSortedByTitle' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, StudyMaterial))],
        ['query'],
      ),
    'getAllTestSeries' : IDL.Func([], [IDL.Vec(TestSeries)], ['query']),
    'getAllTestSeriesSortedByTitle' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, TestSeries))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourseById' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getLiveClassById' : IDL.Func([IDL.Nat], [IDL.Opt(LiveClass)], ['query']),
    'getMyProgress' : IDL.Func([], [IDL.Opt(StudentProgress)], ['query']),
    'getStudyMaterialById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(StudyMaterial)],
        ['query'],
      ),
    'getTestSeriesById' : IDL.Func([IDL.Nat], [IDL.Opt(TestSeries)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSampleData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCompletionPercentage' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateCourse' : IDL.Func([IDL.Nat, Course], [], []),
    'updateLiveClass' : IDL.Func([IDL.Nat, LiveClass], [], []),
    'updateStudyMaterial' : IDL.Func([IDL.Nat, StudyMaterial], [], []),
    'updateTestSeries' : IDL.Func([IDL.Nat, TestSeries], [], []),
  });
};

export const init = ({ IDL }) => { return []; };