/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'title' : string,
  'subjectTags' : Array<string>,
  'description' : string,
  'category' : string,
}
export interface LiveClass {
  'title' : string,
  'scheduledTime' : Time,
  'teacher' : string,
  'isLive' : boolean,
}
export interface StudentProgress {
  'completionPercentage' : bigint,
  'enrolledCourses' : Array<bigint>,
}
export interface StudyMaterial {
  'title' : string,
  'subject' : string,
  'chapter' : string,
}
export interface TestSeries {
  'totalMarks' : bigint,
  'title' : string,
  'subject' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCourse' : ActorMethod<[Course], bigint>,
  'addLiveClass' : ActorMethod<[LiveClass], bigint>,
  'addStudyMaterial' : ActorMethod<[StudyMaterial], bigint>,
  'addTestSeries' : ActorMethod<[TestSeries], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCourse' : ActorMethod<[bigint], undefined>,
  'deleteLiveClass' : ActorMethod<[bigint], undefined>,
  'deleteStudyMaterial' : ActorMethod<[bigint], undefined>,
  'deleteTestSeries' : ActorMethod<[bigint], undefined>,
  'enrollInCourse' : ActorMethod<[bigint], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllCoursesSortedByTitle' : ActorMethod<[], Array<[bigint, Course]>>,
  'getAllLiveClasses' : ActorMethod<[], Array<LiveClass>>,
  'getAllLiveClassesSortedByTime' : ActorMethod<[], Array<[bigint, LiveClass]>>,
  'getAllStudyMaterials' : ActorMethod<[], Array<StudyMaterial>>,
  'getAllStudyMaterialsSortedByTitle' : ActorMethod<
    [],
    Array<[bigint, StudyMaterial]>
  >,
  'getAllTestSeries' : ActorMethod<[], Array<TestSeries>>,
  'getAllTestSeriesSortedByTitle' : ActorMethod<
    [],
    Array<[bigint, TestSeries]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourseById' : ActorMethod<[bigint], [] | [Course]>,
  'getLiveClassById' : ActorMethod<[bigint], [] | [LiveClass]>,
  'getMyProgress' : ActorMethod<[], [] | [StudentProgress]>,
  'getStudyMaterialById' : ActorMethod<[bigint], [] | [StudyMaterial]>,
  'getTestSeriesById' : ActorMethod<[bigint], [] | [TestSeries]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSampleData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCompletionPercentage' : ActorMethod<[bigint, bigint], undefined>,
  'updateCourse' : ActorMethod<[bigint, Course], undefined>,
  'updateLiveClass' : ActorMethod<[bigint, LiveClass], undefined>,
  'updateStudyMaterial' : ActorMethod<[bigint, StudyMaterial], undefined>,
  'updateTestSeries' : ActorMethod<[bigint, TestSeries], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];